version: "3"
services:
    php:
        build: ./docker/dev/php
        image: wexnzbot:app
        expose:
            - "9000"
        volumes:
            - ./app:/var/www
        environment:
            XDEBUG_CONFIG: "remote_host=172.29.175.8"
            PHP_IDE_CONFIG: "serverName=wexnzbot"
        tty: true
        hostname: app
        networks:
            - wexnzbot_net

networks:
    wexnzbot_net: